create or replace PACKAGE FND_API AUTHID DEFINER AS

	G_MISS_NUM  	CONSTANT    NUMBER  	:= 9.99E125;
	G_MISS_CHAR   	CONSTANT    VARCHAR2(1) := chr(0);
	G_MISS_DATE    	CONSTANT    DATE    	:= TO_DATE('1','j');

	G_RET_STS_SUCCESS   	CONSTANT    VARCHAR2(1)	:=  'S';
	G_RET_STS_ERROR	      	CONSTANT    VARCHAR2(1)	:=  'E';
	G_RET_STS_UNEXP_ERROR  	CONSTANT    VARCHAR2(1)	:=  'U';
	
	G_TRUE	    CONSTANT	VARCHAR2(1) := 'T';
	G_FALSE	    CONSTANT	VARCHAR2(1) := 'F';
	
	G_VALID_LEVEL_NONE  CONSTANT	NUMBER := 0;
	G_VALID_LEVEL_FULL  CONSTANT	NUMBER := 100;

END FND_API;
/

create or replace PACKAGE BODY FND_API AS
END FND_API;
/