-- Create table
CREATE TABLE TB_LANCES 
(
  ID              INTEGER       NOT NULL 
, LEILAO_ID       INTEGER       NOT NULL 
, USUARIO_NOME    VARCHAR2(255) NOT NULL 
, VALOR           NUMBER(14,2)  NOT NULL 
, CRIADO_EM       DATE          NOT NULL 
, CONSTRAINT TB_LANCES_PK PRIMARY KEY (ID) ENABLE 
);

CREATE SEQUENCE SEQ_TB_LANCES
	START WITH   1
	INCREMENT BY 1
	NOCACHE
	NOCYCLE;
