/**
 * CRIA VIEWS
 */
CREATE OR REPLACE VIEW FND_LOOKUP_VALUES_VL AS
SELECT B.ROWID ROW_ID,
       B.ATTRIBUTE_CATEGORY,
       B.ATTRIBUTE1,
       B.ATTRIBUTE2,
       B.ATTRIBUTE3,
       B.ATTRIBUTE4,
       B.ATTRIBUTE5,
       B.TERRITORY_CODE,
       B.ATTRIBUTE6,
       B.ATTRIBUTE7,
       B.ATTRIBUTE8,
       B.ATTRIBUTE9,
       B.ATTRIBUTE10,
       B.ATTRIBUTE11,
       B.ATTRIBUTE12,
       B.ATTRIBUTE13,
       B.ATTRIBUTE14,
       B.ATTRIBUTE15,
       B.LOOKUP_TYPE,
       B.LOOKUP_CODE,
       B.ENABLED_FLAG,
       B.START_DATE_ACTIVE,
       B.END_DATE_ACTIVE,
       B.CREATED_BY,
       B.CREATION_DATE,
       B.LAST_UPDATED_BY,
       B.LAST_UPDATE_LOGIN,
       B.LAST_UPDATE_DATE,
       B.SECURITY_GROUP_ID,
       B.VIEW_APPLICATION_ID,
       B.TAG,
       B.MEANING,
       B.DESCRIPTION
  from FND_LOOKUP_VALUES B
 WHERE B.LANGUAGE = userenv('LANG');
 
/******************/
CREATE OR REPLACE VIEW WSH_CARRIER_SERVICES_V
(row_id, carrier_service_id, carrier_id, service_level, mode_of_transport, sl_time_uom, min_sl_time, max_sl_time, enabled_flag, web_enabled, ship_method_code, ship_method_meaning, attribute_category, attribute1, attribute2, attribute3, attribute4, attribute5, attribute6, attribute7, attribute8, attribute9, attribute10, attribute11, attribute12, attribute13, attribute14, attribute15, creation_date, created_by, last_update_date, last_updated_by, last_update_login, program_application_id, program_id, program_update_date, request_id, max_num_stops_permitted, max_total_distance, max_total_time, allow_intersperse_load, max_layover_time, min_layover_time, max_total_distance_in_24hr, allow_continuous_move, max_cm_distance, max_cm_time, max_cm_dh_distance, max_cm_dh_time, max_size_length, max_size_width, max_size_height, min_size_length, min_size_width, min_size_height, max_out_of_route, cm_free_dh_mileage, min_cm_distance, cm_first_load_discount, min_cm_time, unit_rate_basis, cm_rate_variant, distance_calculation_method, origin_dstn_surcharge_level, max_driving_time_in_24hr, max_duty_time_in_24hr)
AS
SELECT WCS.ROWID,
       WCS.CARRIER_SERVICE_ID,
       WCS.CARRIER_ID,
       WCS.SERVICE_LEVEL,
       WCS.MODE_OF_TRANSPORT,
       WCS.SL_TIME_UOM,
       WCS.MIN_SL_TIME,
       WCS.MAX_SL_TIME,
       WCS.ENABLED_FLAG,
       WCS.WEB_ENABLED,
       WCS.SHIP_METHOD_CODE,
       FL.MEANING SHIP_METHOD_MEANING,
       WCS.ATTRIBUTE_CATEGORY,
       WCS.ATTRIBUTE1,
       WCS.ATTRIBUTE2,
       WCS.ATTRIBUTE3,
       WCS.ATTRIBUTE4,
       WCS.ATTRIBUTE5,
       WCS.ATTRIBUTE6,
       WCS.ATTRIBUTE7,
       WCS.ATTRIBUTE8,
       WCS.ATTRIBUTE9,
       WCS.ATTRIBUTE10,
       WCS.ATTRIBUTE11,
       WCS.ATTRIBUTE12,
       WCS.ATTRIBUTE13,
       WCS.ATTRIBUTE14,
       WCS.ATTRIBUTE15,
       WCS.CREATION_DATE,
       WCS.CREATED_BY,
       WCS.LAST_UPDATE_DATE,
       WCS.LAST_UPDATED_BY,
       WCS.LAST_UPDATE_LOGIN,
       WCS.PROGRAM_APPLICATION_ID,
       WCS.PROGRAM_ID,
       WCS.PROGRAM_UPDATE_DATE,
       WCS.REQUEST_ID,
       WCS.MAX_NUM_STOPS_PERMITTED,
       WCS.MAX_TOTAL_DISTANCE,
       WCS.MAX_TOTAL_TIME,
       WCS.ALLOW_INTERSPERSE_LOAD,
       WCS.MAX_LAYOVER_TIME,
       WCS.MIN_LAYOVER_TIME,
       WCS.MAX_TOTAL_DISTANCE_IN_24HR,
       WCS.ALLOW_CONTINUOUS_MOVE,
       WCS.MAX_CM_DISTANCE,
       WCS.MAX_CM_TIME,
       WCS.MAX_CM_DH_DISTANCE,
       WCS.MAX_CM_DH_TIME,
       WCS.MAX_SIZE_LENGTH,
       WCS.MAX_SIZE_WIDTH,
       WCS.MAX_SIZE_HEIGHT,
       WCS.MIN_SIZE_LENGTH,
       WCS.MIN_SIZE_WIDTH,
       WCS.MIN_SIZE_HEIGHT,
       WCS.MAX_OUT_OF_ROUTE,
       WCS.CM_FREE_DH_MILEAGE,
       WCS.MIN_CM_DISTANCE,
       WCS.CM_FIRST_LOAD_DISCOUNT,
       WCS.MIN_CM_TIME,
       WCS.UNIT_RATE_BASIS,
       WCS.CM_RATE_VARIANT,
       WCS.DISTANCE_CALCULATION_METHOD,
       WCS.ORIGIN_DSTN_SURCHARGE_LEVEL,
       WCS.MAX_DRIVING_TIME_IN_24HR,
       WCS.MAX_DUTY_TIME_IN_24HR
  FROM WSH_CARRIER_SERVICES WCS, FND_LOOKUP_VALUES_VL FL
 WHERE FL.LOOKUP_TYPE = 'SHIP_METHOD'
   AND FL. LOOKUP_CODE = WCS.SHIP_METHOD_CODE
   AND FL.VIEW_APPLICATION_ID = 3;
   
/*view que usa a tabela HZ_CUST_SITE_USES_ALL*/
CREATE OR REPLACE VIEW RA_SITE_USES_MORG
(
	site_use_id, last_update_date, last_updated_by, creation_date, created_by, site_use_code, 
	address_id, primary_flag, status, location, last_update_login, contact_id, bill_to_site_use_id, 
	orig_system_reference, sic_code, payment_term_id, gsa_indicator, ship_partial, ship_via, fob_point, 
	order_type_id, price_list_id, freight_term, warehouse_id, territory_id, attribute_category, attribute1, 
	attribute2, attribute3, attribute4, attribute5, attribute6, attribute7, attribute8, attribute9, attribute10, 
	request_id, program_application_id, program_id, program_update_date, tax_reference, sort_priority, tax_code, 
	attribute11, attribute12, attribute13, attribute14, attribute15, attribute16, attribute17, attribute18, 
	attribute19, attribute20, attribute21, attribute22, attribute23, attribute24, attribute25, 
	last_accrue_charge_date, second_last_accrue_charge_date, last_unaccrue_charge_date, 
	second_last_unaccrue_chrg_date, demand_class_code, tax_exempt, tax_exempt_num, tax_exempt_reason_code, 
	org_id, tax_classification, tax_header_level_flag, tax_rounding_rule, wh_update_date, global_attribute1, 
	global_attribute2, global_attribute3, global_attribute4, global_attribute5, global_attribute6, 
	global_attribute7, global_attribute8, global_attribute9, global_attribute10, global_attribute11, 
	global_attribute12, global_attribute13, global_attribute14, global_attribute15, global_attribute16, 
	global_attribute17, global_attribute18, global_attribute19, global_attribute20, global_attribute_category, 
	primary_salesrep_id, finchrg_receivables_trx_id, gl_id_rec, gl_id_rev, gl_id_tax, gl_id_freight, 
	gl_id_clearing, gl_id_unbilled, gl_id_unearned, gl_id_unpaid_rec, gl_id_remittance, gl_id_factor, 
	dates_negative_tolerance, dates_positive_tolerance, date_type_preference, over_shipment_tolerance, 
	under_shipment_tolerance, item_cross_ref_pref, over_return_tolerance, under_return_tolerance, 
	ship_sets_include_lines_flag, arrivalsets_include_lines_flag, sched_date_push_flag, invoice_quantity_rule, 
	pricing_event)
AS
SELECT SITE_USE_ID,
       LAST_UPDATE_DATE,
       LAST_UPDATED_BY,
       CREATION_DATE,
       CREATED_BY,
       SITE_USE_CODE,
       CUST_ACCT_SITE_ID /* ADDRESS_ID */,
       PRIMARY_FLAG,
       STATUS,
       LOCATION,
       LAST_UPDATE_LOGIN,
       CONTACT_ID,
       BILL_TO_SITE_USE_ID,
       ORIG_SYSTEM_REFERENCE,
       SIC_CODE,
       PAYMENT_TERM_ID,
       GSA_INDICATOR,
       SHIP_PARTIAL,
       SHIP_VIA,
       FOB_POINT,
       ORDER_TYPE_ID,
       PRICE_LIST_ID,
       FREIGHT_TERM,
       WAREHOUSE_ID,
       TERRITORY_ID,
       ATTRIBUTE_CATEGORY,
       ATTRIBUTE1,
       ATTRIBUTE2,
       ATTRIBUTE3,
       ATTRIBUTE4,
       ATTRIBUTE5,
       ATTRIBUTE6,
       ATTRIBUTE7,
       ATTRIBUTE8,
       ATTRIBUTE9,
       ATTRIBUTE10,
       REQUEST_ID,
       PROGRAM_APPLICATION_ID,
       PROGRAM_ID,
       PROGRAM_UPDATE_DATE,
       TAX_REFERENCE,
       SORT_PRIORITY,
       TAX_CODE,
       ATTRIBUTE11,
       ATTRIBUTE12,
       ATTRIBUTE13,
       ATTRIBUTE14,
       ATTRIBUTE15,
       ATTRIBUTE16,
       ATTRIBUTE17,
       ATTRIBUTE18,
       ATTRIBUTE19,
       ATTRIBUTE20,
       ATTRIBUTE21,
       ATTRIBUTE22,
       ATTRIBUTE23,
       ATTRIBUTE24,
       ATTRIBUTE25,
       LAST_ACCRUE_CHARGE_DATE,
       SECOND_LAST_ACCRUE_CHARGE_DATE,
       LAST_UNACCRUE_CHARGE_DATE,
       SECOND_LAST_UNACCRUE_CHRG_DATE,
       DEMAND_CLASS_CODE,
       NULL /* TAX_EXEMPT (no longer used) */,
       NULL /* TAX_EXEMPT_NUM (no longer used) */,
       NULL /* TAX_EXEMPT_REASON_CODE (no longer used) */,
       ORG_ID,
       TAX_CLASSIFICATION /* Added - Bug 1335212 */,
       TAX_HEADER_LEVEL_FLAG,
       TAX_ROUNDING_RULE,
       WH_UPDATE_DATE,
       GLOBAL_ATTRIBUTE1,
       GLOBAL_ATTRIBUTE2,
       GLOBAL_ATTRIBUTE3,
       GLOBAL_ATTRIBUTE4,
       GLOBAL_ATTRIBUTE5,
       GLOBAL_ATTRIBUTE6,
       GLOBAL_ATTRIBUTE7,
       GLOBAL_ATTRIBUTE8,
       GLOBAL_ATTRIBUTE9,
       GLOBAL_ATTRIBUTE10,
       GLOBAL_ATTRIBUTE11,
       GLOBAL_ATTRIBUTE12,
       GLOBAL_ATTRIBUTE13,
       GLOBAL_ATTRIBUTE14,
       GLOBAL_ATTRIBUTE15,
       GLOBAL_ATTRIBUTE16,
       GLOBAL_ATTRIBUTE17,
       GLOBAL_ATTRIBUTE18,
       GLOBAL_ATTRIBUTE19,
       GLOBAL_ATTRIBUTE20,
       GLOBAL_ATTRIBUTE_CATEGORY,
       PRIMARY_SALESREP_ID,
       FINCHRG_RECEIVABLES_TRX_ID,
       GL_ID_REC,
       GL_ID_REV,
       GL_ID_TAX,
       GL_ID_FREIGHT,
       GL_ID_CLEARING,
       GL_ID_UNBILLED,
       GL_ID_UNEARNED,
       GL_ID_UNPAID_REC,
       GL_ID_REMITTANCE,
       GL_ID_FACTOR,
       DATES_NEGATIVE_TOLERANCE,
       DATES_POSITIVE_TOLERANCE,
       DATE_TYPE_PREFERENCE,
       OVER_SHIPMENT_TOLERANCE,
       UNDER_SHIPMENT_TOLERANCE,
       ITEM_CROSS_REF_PREF,
       OVER_RETURN_TOLERANCE,
       UNDER_RETURN_TOLERANCE,
       SHIP_SETS_INCLUDE_LINES_FLAG,
       ARRIVALSETS_INCLUDE_LINES_FLAG,
       SCHED_DATE_PUSH_FLAG,
       INVOICE_QUANTITY_RULE,
       PRICING_EVENT
  FROM HZ_CUST_SITE_USES_ALL;
  
  
CREATE SYNONYM RA_SITE_USES_ALL FOR RA_SITE_USES_MORG;

/*View de uso da tabela */  
CREATE OR REPLACE VIEW RA_ADDRESSES_MORG
(
	row_id, party_site_id, party_id, party_location_id, key_account_flag, program_update_date, territory_id, 
	address_key, bill_to_flag, market_flag, ship_to_flag, attribute11, attribute12, attribute13, attribute14, 
	attribute15, location_id, service_territory_id, primary_specialist_id, secondary_specialist_id, 
	customer_category_code, customer_group_code, customer_subgroup_code, reference_use_flag, analysis_fy, 
	fiscal_yearend_month, net_worth, num_of_employees, potential_revenue_curr_fy, potential_revenue_next_fy, 
	rank, competitor_flag, third_party_flag, year_established, do_not_mail_flag, address_style, language, 
	address_id, last_update_date, last_updated_by, creation_date, created_by, customer_id, status, 
	orig_system_reference, org_id, country, address1, address2, address3, address4, city, postal_code, 
	state, province, county, last_update_login, attribute_category, attribute1, attribute2, attribute3, 
	attribute4, attribute5, attribute6, attribute7, attribute8, attribute9, attribute10, request_id, 
	program_application_id, program_id, address_lines_phonetic, global_attribute1, global_attribute2, 
	global_attribute3, global_attribute4, global_attribute5, global_attribute6, global_attribute7, 
	global_attribute8, global_attribute9, global_attribute10, global_attribute11, global_attribute12, 
	global_attribute13, global_attribute14, global_attribute15, global_attribute16, global_attribute17, 
	global_attribute18, global_attribute19, global_attribute_category, tp_header_id, wh_update_date, 
	global_attribute20, ece_tp_location_code, sales_tax_geocode, sales_tax_inside_city_limits, territory, 
	translated_customer_name, address_text, site_number, identifying_address_flag, attribute16, attribute17, 
	attribute18, attribute19, attribute20, party_site_last_update_date, loc_last_update_date, addressee)
AS
SELECT ACCT_SITE.ROWID,
       PARTY_SITE.PARTY_SITE_ID,
       PARTY_SITE.PARTY_ID,
       LOC.LOCATION_ID,
       ACCT_SITE.KEY_ACCOUNT_FLAG,
       ACCT_SITE.PROGRAM_UPDATE_DATE,
       ACCT_SITE.TERRITORY_ID,
       LOC.ADDRESS_KEY,
       ACCT_SITE.BILL_TO_FLAG,
       ACCT_SITE.MARKET_FLAG,
       ACCT_SITE.SHIP_TO_FLAG,
       nvl(ACCT_SITE.ATTRIBUTE11, LOC.ATTRIBUTE11),
       nvl(ACCT_SITE.ATTRIBUTE12, LOC.ATTRIBUTE12),
       nvl(ACCT_SITE.ATTRIBUTE13, LOC.ATTRIBUTE13),
       nvl(ACCT_SITE.ATTRIBUTE14, LOC.ATTRIBUTE14),
       nvl(ACCT_SITE.ATTRIBUTE15, LOC.ATTRIBUTE15),
       LOC_ASSIGN.LOC_ID,
       ACCT_SITE.SERVICE_TERRITORY_ID,
       ACCT_SITE.PRIMARY_SPECIALIST_ID,
       ACCT_SITE.SECONDARY_SPECIALIST_ID,
       ACCT_SITE.CUSTOMER_CATEGORY_CODE,
       NULL,
       NULL,
       NULL,
       NULL,
       NULL,
       TO_NUMBER(NULL),
       TO_NUMBER(NULL),
       TO_NUMBER(NULL),
       TO_NUMBER(NULL),
       NULL,
       NULL,
       NULL,
       TO_NUMBER(NULL),
       NULL,
       LOC.ADDRESS_STYLE,
       LOC.LANGUAGE,
       ACCT_SITE.CUST_ACCT_SITE_ID,
       ACCT_SITE.LAST_UPDATE_DATE,
       ACCT_SITE.LAST_UPDATED_BY,
       ACCT_SITE.CREATION_DATE,
       ACCT_SITE.CREATED_BY,
       ACCT_SITE.CUST_ACCOUNT_ID,
       ACCT_SITE.STATUS,
       ACCT_SITE.ORIG_SYSTEM_REFERENCE,
       ACCT_SITE.ORG_ID,
       LOC.COUNTRY,
       LOC.ADDRESS1,
       LOC.ADDRESS2,
       LOC.ADDRESS3,
       LOC.ADDRESS4,
       LOC.CITY,
       LOC.POSTAL_CODE,
       LOC.STATE,
       LOC.PROVINCE,
       LOC.COUNTY,
       ACCT_SITE.LAST_UPDATE_LOGIN,
       ACCT_SITE.ATTRIBUTE_CATEGORY,
       ACCT_SITE.ATTRIBUTE1,
       ACCT_SITE.ATTRIBUTE2,
       ACCT_SITE.ATTRIBUTE3,
       ACCT_SITE.ATTRIBUTE4,
       ACCT_SITE.ATTRIBUTE5,
       ACCT_SITE.ATTRIBUTE6,
       ACCT_SITE.ATTRIBUTE7,
       ACCT_SITE.ATTRIBUTE8,
       ACCT_SITE.ATTRIBUTE9,
       ACCT_SITE.ATTRIBUTE10,
       ACCT_SITE.REQUEST_ID,
       ACCT_SITE.PROGRAM_APPLICATION_ID,
       ACCT_SITE.PROGRAM_ID,
       LOC.ADDRESS_LINES_PHONETIC,
       ACCT_SITE.GLOBAL_ATTRIBUTE1,
       ACCT_SITE.GLOBAL_ATTRIBUTE2,
       ACCT_SITE.GLOBAL_ATTRIBUTE3,
       ACCT_SITE.GLOBAL_ATTRIBUTE4,
       ACCT_SITE.GLOBAL_ATTRIBUTE5,
       ACCT_SITE.GLOBAL_ATTRIBUTE6,
       ACCT_SITE.GLOBAL_ATTRIBUTE7,
       ACCT_SITE.GLOBAL_ATTRIBUTE8,
       ACCT_SITE.GLOBAL_ATTRIBUTE9,
       ACCT_SITE.GLOBAL_ATTRIBUTE10,
       ACCT_SITE.GLOBAL_ATTRIBUTE11,
       ACCT_SITE.GLOBAL_ATTRIBUTE12,
       ACCT_SITE.GLOBAL_ATTRIBUTE13,
       ACCT_SITE.GLOBAL_ATTRIBUTE14,
       ACCT_SITE.GLOBAL_ATTRIBUTE15,
       ACCT_SITE.GLOBAL_ATTRIBUTE16,
       ACCT_SITE.GLOBAL_ATTRIBUTE17,
       ACCT_SITE.GLOBAL_ATTRIBUTE18,
       ACCT_SITE.GLOBAL_ATTRIBUTE19,
       ACCT_SITE.GLOBAL_ATTRIBUTE_CATEGORY,
       ACCT_SITE.TP_HEADER_ID,
       ACCT_SITE.WH_UPDATE_DATE,
       ACCT_SITE.GLOBAL_ATTRIBUTE20,
       ACCT_SITE.ECE_TP_LOCATION_CODE,
       LOC.SALES_TAX_GEOCODE,
       LOC.SALES_TAX_INSIDE_CITY_LIMITS,
       ACCT_SITE.TERRITORY,
       ACCT_SITE.TRANSLATED_CUSTOMER_NAME,
       ACCT_SITE.ADDRESS_TEXT,
       PARTY_SITE.PARTY_SITE_NUMBER,
       PARTY_SITE.IDENTIFYING_ADDRESS_FLAG,
       ACCT_SITE.ATTRIBUTE16,
       ACCT_SITE.ATTRIBUTE17,
       ACCT_SITE.ATTRIBUTE18,
       ACCT_SITE.ATTRIBUTE19,
       ACCT_SITE.ATTRIBUTE20,
       PARTY_SITE.LAST_UPDATE_DATE,
       LOC.LAST_UPDATE_DATE,
       PARTY_SITE.ADDRESSEE
  FROM HZ_PARTY_SITES         PARTY_SITE,
       HZ_LOC_ASSIGNMENTS     LOC_ASSIGN,
       HZ_LOCATIONS           LOC,
       HZ_CUST_ACCT_SITES_ALL   ACCT_SITE
 WHERE ACCT_SITE.PARTY_SITE_ID = PARTY_SITE.PARTY_SITE_ID
   AND LOC.LOCATION_ID = PARTY_SITE.LOCATION_ID
   AND LOC.LOCATION_ID = LOC_ASSIGN.LOCATION_ID
   AND NVL(ACCT_SITE.ORG_ID, -99) = NVL(LOC_ASSIGN.ORG_ID, -99);
  
CREATE SYNONYM ra_addresses_all FOR RA_ADDRESSES_MORG;


CREATE OR REPLACE VIEW RA_HCUSTOMERS
(row_id, customer_id, party_id, party_number, party_type, last_update_date, last_updated_by, creation_date, 
created_by, customer_name, customer_number, orig_system_reference, status, last_update_login, customer_type, 
customer_prospect_code, customer_class_code, primary_salesrep_id, sales_channel_code, sic_code, order_type_id,
price_list_id, attribute_category, attribute1, attribute2, attribute3, attribute4, attribute5, attribute6, 
attribute7, attribute8, attribute9, attribute10, request_id, program_application_id, program_id, program_update_date, 
analysis_fy, customer_category_code, customer_group_code, customer_key, customer_subgroup_code, fiscal_yearend_month,
net_worth, num_of_employees, potential_revenue_curr_fy, potential_revenue_next_fy, rank, reference_use_flag, 
tax_code, tax_reference, attribute11, attribute12, attribute13, attribute14, attribute15, third_party_flag, 
access_template_entity_code, primary_specialist_id, secondary_specialist_id, competitor_flag, dunning_site_use_id,
statement_site_use_id, orig_system, year_established, coterminate_day_month, fob_point, freight_term, gsa_indicator,
ship_partial, ship_via, warehouse_id, payment_term_id, tax_exempt, tax_exempt_num, tax_exempt_reason_code, 
jgzz_fiscal_code, do_not_mail_flag, mission_statement, customer_name_phonetic, tax_header_level_flag,
tax_rounding_rule, wh_update_date, global_attribute1, global_attribute2, global_attribute3, global_attribute4, 
global_attribute5, global_attribute6, global_attribute7, global_attribute8, global_attribute9, global_attribute10, 
global_attribute11, global_attribute12, global_attribute13, global_attribute14, global_attribute15,
global_attribute16, global_attribute17, global_attribute18, global_attribute19, global_attribute20, 
global_attribute_category, url, language, translated_customer_name, person_pre_name_adjunct, 
person_first_name, person_middle_name, person_last_name, person_suffix, person_first_name_phonetic, 
person_last_name_phonetic, ship_sets_include_lines_flag, arrivalsets_include_lines_flag,
sched_date_push_flag, over_shipment_tolerance, under_shipment_tolerance, over_return_tolerance,
under_return_tolerance, item_cross_ref_pref, date_type_preference, dates_negative_tolerance, 
dates_positive_tolerance, invoice_quantity_rule, attribute16, attribute17, attribute18, attribute19, 
attribute20, duns_number, duns_number_c, party_last_update_date, sic_code_type)
AS
SELECT CUST_ACCT.ROWID,
       CUST_ACCT.CUST_ACCOUNT_ID,
       PARTY.PARTY_ID,
       PARTY.PARTY_NUMBER,
       PARTY.PARTY_TYPE,
       CUST_ACCT.LAST_UPDATE_DATE,
       CUST_ACCT.LAST_UPDATED_BY,
       CUST_ACCT.CREATION_DATE,
       CUST_ACCT.CREATED_BY,
       substrb(PARTY.PARTY_NAME, 1, 50) /* customer_name */,
       CUST_ACCT.ACCOUNT_NUMBER /* customer number */,
       CUST_ACCT.ORIG_SYSTEM_REFERENCE,
       CUST_ACCT.STATUS,
       CUST_ACCT.LAST_UPDATE_LOGIN,
       CUST_ACCT.CUSTOMER_TYPE,
       'CUSTOMER',
       CUST_ACCT.CUSTOMER_CLASS_CODE,
       CUST_ACCT.PRIMARY_SALESREP_ID,
       CUST_ACCT.SALES_CHANNEL_CODE,
       DECODE(PARTY.PARTY_TYPE, 'ORGANIZATION', PARTY.SIC_CODE, NULL),
       CUST_ACCT.ORDER_TYPE_ID,
       CUST_ACCT.PRICE_LIST_ID,
       CUST_ACCT.ATTRIBUTE_CATEGORY,
       CUST_ACCT.ATTRIBUTE1,
       CUST_ACCT.ATTRIBUTE2,
       CUST_ACCT.ATTRIBUTE3,
       CUST_ACCT.ATTRIBUTE4,
       CUST_ACCT.ATTRIBUTE5,
       CUST_ACCT.ATTRIBUTE6,
       CUST_ACCT.ATTRIBUTE7,
       CUST_ACCT.ATTRIBUTE8,
       CUST_ACCT.ATTRIBUTE9,
       CUST_ACCT.ATTRIBUTE10,
       CUST_ACCT.REQUEST_ID,
       CUST_ACCT.PROGRAM_APPLICATION_ID,
       CUST_ACCT.PROGRAM_ID,
       CUST_ACCT.PROGRAM_UPDATE_DATE,
       DECODE(PARTY.PARTY_TYPE, 'ORGANIZATION', PARTY.ANALYSIS_FY, NULL),
       PARTY.CATEGORY_CODE,
       NULL /* CUSTOMER_GROUP_CODE (no longer used) */,
       PARTY.CUSTOMER_KEY,
       NULL /* CUSTOMER_SUBGROUP_CODE (no longer used) */,
       DECODE(PARTY.PARTY_TYPE,
              'ORGANIZATION',
              PARTY.FISCAL_YEAREND_MONTH,
              NULL),
       TO_NUMBER(NULL) /* NET_WORTH (no longer used) */,
       DECODE(PARTY.PARTY_TYPE,
              'ORGANIZATION',
              PARTY.EMPLOYEES_TOTAL,
              TO_NUMBER(NULL)),
       DECODE(PARTY.PARTY_TYPE,
              'ORGANIZATION',
              PARTY.CURR_FY_POTENTIAL_REVENUE,
              TO_NUMBER(NULL)),
       DECODE(PARTY.PARTY_TYPE,
              'ORGANIZATION',
              PARTY.NEXT_FY_POTENTIAL_REVENUE,
              TO_NUMBER(NULL)),
       NULL,
       PARTY.REFERENCE_USE_FLAG,
       CUST_ACCT.TAX_CODE,
       PARTY.TAX_REFERENCE,
       CUST_ACCT.ATTRIBUTE11,
       CUST_ACCT.ATTRIBUTE12,
       CUST_ACCT.ATTRIBUTE13,
       CUST_ACCT.ATTRIBUTE14,
       CUST_ACCT.ATTRIBUTE15,
       PARTY.THIRD_PARTY_FLAG,
       NULL /* ACCESS_TEMPLATE_ENTITY_CODE */,
       CUST_ACCT.PRIMARY_SPECIALIST_ID,
       CUST_ACCT.SECONDARY_SPECIALIST_ID,
       PARTY.COMPETITOR_FLAG,
       TO_NUMBER(NULL) /* DUNNING_SITE_USE_ID */,
       TO_NUMBER(NULL) /* STATEMENT_SITE_USE_ID */,
       NULL /* ORIG_SYSTEM */,
       DECODE(PARTY.PARTY_TYPE,
              'ORGANIZATION',
              PARTY.YEAR_ESTABLISHED,
              TO_NUMBER(NULL)),
       CUST_ACCT.COTERMINATE_DAY_MONTH,
       CUST_ACCT.FOB_POINT,
       CUST_ACCT.FREIGHT_TERM,
       DECODE(PARTY.PARTY_TYPE,
              'ORGANIZATION',
              PARTY.GSA_INDICATOR_FLAG,
              'N'),
       CUST_ACCT.SHIP_PARTIAL,
       CUST_ACCT.SHIP_VIA,
       CUST_ACCT.WAREHOUSE_ID,
       CUST_ACCT.PAYMENT_TERM_ID,
       NULL /* TAX_EXEMPT (no longer used) */,
       NULL /* TAX_EXEMPT_NUM (no longer used) */,
       NULL /* TAX_EXEMPT_REASON_CODE (no longer used) */,
       PARTY.JGZZ_FISCAL_CODE,
       PARTY.DO_NOT_MAIL_FLAG /* DO_NOT_MAIL_FLAG */,
       DECODE(PARTY.PARTY_TYPE,
              'ORGANIZATION',
              PARTY.MISSION_STATEMENT,
              NULL),
       DECODE(PARTY.PARTY_TYPE,
              'ORGANIZATION',
              PARTY.ORGANIZATION_NAME_PHONETIC,
              NULL) /* CUSTOMER_NAME_PHONETIC */,
       CUST_ACCT.TAX_HEADER_LEVEL_FLAG,
       CUST_ACCT.TAX_ROUNDING_RULE,
       CUST_ACCT.WH_UPDATE_DATE,
       CUST_ACCT.GLOBAL_ATTRIBUTE1,
       CUST_ACCT.GLOBAL_ATTRIBUTE2,
       CUST_ACCT.GLOBAL_ATTRIBUTE3,
       CUST_ACCT.GLOBAL_ATTRIBUTE4,
       CUST_ACCT.GLOBAL_ATTRIBUTE5,
       CUST_ACCT.GLOBAL_ATTRIBUTE6,
       CUST_ACCT.GLOBAL_ATTRIBUTE7,
       CUST_ACCT.GLOBAL_ATTRIBUTE8,
       CUST_ACCT.GLOBAL_ATTRIBUTE9,
       CUST_ACCT.GLOBAL_ATTRIBUTE10,
       CUST_ACCT.GLOBAL_ATTRIBUTE11,
       CUST_ACCT.GLOBAL_ATTRIBUTE12,
       CUST_ACCT.GLOBAL_ATTRIBUTE13,
       CUST_ACCT.GLOBAL_ATTRIBUTE14,
       CUST_ACCT.GLOBAL_ATTRIBUTE15,
       CUST_ACCT.GLOBAL_ATTRIBUTE16,
       CUST_ACCT.GLOBAL_ATTRIBUTE17,
       CUST_ACCT.GLOBAL_ATTRIBUTE18,
       CUST_ACCT.GLOBAL_ATTRIBUTE19,
       CUST_ACCT.GLOBAL_ATTRIBUTE20,
       CUST_ACCT.GLOBAL_ATTRIBUTE_CATEGORY,
       PARTY.URL,
       NULL /* LANGUAGE */,
       NULL /* TRANSLATED_CUSTOMER_NAME */,
       PARTY.PERSON_PRE_NAME_ADJUNCT /* PREFIX */,
       PARTY.PERSON_FIRST_NAME,
       PARTY.PERSON_MIDDLE_NAME,
       PARTY.PERSON_LAST_NAME,
       PARTY.PERSON_NAME_SUFFIX,
       DECODE(PARTY.PARTY_TYPE,
              'PERSON',
              PARTY.PERSON_FIRST_NAME_PHONETIC,
              NULL),
       DECODE(PARTY.PARTY_TYPE,
              'PERSON',
              PARTY.PERSON_LAST_NAME_PHONETIC,
              NULL),
       CUST_ACCT.SHIP_SETS_INCLUDE_LINES_FLAG,
       CUST_ACCT.ARRIVALSETS_INCLUDE_LINES_FLAG,
       CUST_ACCT.SCHED_DATE_PUSH_FLAG,
       CUST_ACCT.OVER_SHIPMENT_TOLERANCE,
       CUST_ACCT.UNDER_SHIPMENT_TOLERANCE,
       CUST_ACCT.OVER_RETURN_TOLERANCE,
       CUST_ACCT.UNDER_RETURN_TOLERANCE,
       CUST_ACCT.ITEM_CROSS_REF_PREF,
       CUST_ACCT.DATE_TYPE_PREFERENCE,
       CUST_ACCT.DATES_NEGATIVE_TOLERANCE,
       CUST_ACCT.DATES_POSITIVE_TOLERANCE,
       CUST_ACCT.INVOICE_QUANTITY_RULE,
       CUST_ACCT.ATTRIBUTE16,
       CUST_ACCT.ATTRIBUTE17,
       CUST_ACCT.ATTRIBUTE18,
       CUST_ACCT.ATTRIBUTE19,
       CUST_ACCT.ATTRIBUTE20,
       DECODE(PARTY.PARTY_TYPE, 'ORGANIZATION', PARTY.DUNS_NUMBER, NULL),
       DECODE(PARTY.PARTY_TYPE, 'ORGANIZATION', PARTY.DUNS_NUMBER_C, NULL),
       PARTY.LAST_UPDATE_DATE,
       DECODE(PARTY.PARTY_TYPE, 'ORGANIZATION', PARTY.SIC_CODE_TYPE, NULL)
  FROM HZ_PARTIES      PARTY, 
       HZ_CUST_ACCOUNTS     CUST_ACCT
 WHERE CUST_ACCT.PARTY_ID = PARTY.PARTY_ID;
 
 
CREATE SYNONYM ra_customers FOR RA_HCUSTOMERS;


CREATE OR REPLACE VIEW HR_LOOKUPS
(application_id, lookup_type, lookup_code, meaning, last_update_date, last_updated_by, enabled_flag, start_date_active, end_date_active, description, last_update_login, created_by, creation_date)
AS
SELECT DECODE(SUBSTR(FLV.LOOKUP_TYPE, 1, 3), 'HXT', 808, 800),
       FLV.LOOKUP_TYPE,
       FLV.LOOKUP_CODE,
       FLV.MEANING,
       FLV.LAST_UPDATE_DATE,
       FLV.LAST_UPDATED_BY,
       FLV.ENABLED_FLAG,
       FLV.START_DATE_ACTIVE,
       FLV.END_DATE_ACTIVE,
       FLV.DESCRIPTION,
       FLV.LAST_UPDATE_LOGIN,
       FLV.CREATED_BY,
       FLV.CREATION_DATE
  FROM FND_LOOKUP_VALUES FLV
 where FLV.LANGUAGE = userenv('LANG')
   and FLV.VIEW_APPLICATION_ID = 3
   AND (flv.lookup_type, flv.security_group_id) in
       (select lt.lookup_type, max(lt.security_group_id)
          from fnd_lookup_types lt
         where lt.view_application_id = 3
           and lt.security_group_id in
               (0,
                to_number(decode(substrb(userenv('CLIENT_INFO'), 55, 1),
                                 ' ',
                                 '0',
                                 null,
                                 '0',
                                 substrb(userenv('CLIENT_INFO'), 55, 10))))
         group by lt.lookup_type)
   and decode(FLV.TAG,
              NULL,
              'Y',
              decode(substr(FLV.TAG, 1, 1),
                     '+',
                     decode(sign(instr(FLV.TAG,
                                       sys_context('HR_SESSION_DATA',
                                                   'LEG_CODE'))),
                            1,
                            'Y',
                            'N'),
                     '-',
                     decode(sign(instr(FLV.TAG,
                                       sys_context('HR_SESSION_DATA',
                                                   'LEG_CODE'))),
                            1,
                            'N',
                            'Y'),
                     'Y')) = 'Y';
                     
                     
                     

CREATE OR REPLACE VIEW  FND_TIMEZONES_VL AS
SELECT tz.timezone_code,
       tz_tl.name name,
       tz.ENABLED_FLAG,
       tz.GMT_OFFSET,
       tz.DAYLIGHT_SAVINGS_FLAG,
       tz.ACTIVE_TIMEZONE_CODE,
       tz.UPGRADE_TZ_ID,
       tz.CREATION_DATE,
       tz.CREATED_BY,
       tz.LAST_UPDATE_DATE,
       tz.LAST_UPDATED_BY,
       tz.LAST_UPDATE_LOGIN
  from fnd_timezones_b tz, fnd_timezones_tl tz_tl
 WHERE tz.TIMEZONE_CODE = tz_tl.TIMEZONE_CODE
   and tz_tl.language = USERENV('LANG');




CREATE OR REPLACE VIEW  HR_LOCATIONS_V
(tp_header_id, ece_tp_location_code, row_id, location_id, location_code, bill_to_site_flag, country, description, designated_receiver_id, in_organization_flag, inactive_date, inventory_organization_id, office_site_flag, receiving_site_flag, ship_to_location_id, ship_to_site_flag, tax_name, style, ship_to_site, bill_to_site, office_site, receiving_site, internal_site, ship_to_location, address_style, entered_by, address_line_1, address_line_2, address_line_3, postal_code, region_1, region_2, region_3, telephone_number_1, telephone_number_2, telephone_number_3, town_or_city, attribute_category, attribute1, attribute2, attribute3, attribute4, attribute5, attribute6, attribute7, attribute8, attribute9, attribute10, attribute11, attribute12, attribute13, attribute14, attribute15, attribute16, attribute17, attribute18, attribute19, attribute20, global_attribute_category, global_attribute1, global_attribute2, global_attribute3, global_attribute4, global_attribute5, global_attribute6, global_attribute7, global_attribute8, global_attribute9, global_attribute10, global_attribute11, global_attribute12, global_attribute13, global_attribute14, global_attribute15, global_attribute16, global_attribute17, global_attribute18, global_attribute19, global_attribute20, last_update_date, last_updated_by, last_update_login, created_by, creation_date, loc_information13, loc_information14, loc_information15, loc_information16, loc_information17, loc_information18, loc_information19, loc_information20, object_version_number, business_group_id, legal_address_flag, timezone_code, timezone_display)
AS
SELECT L.TP_HEADER_ID,
       L.ECE_TP_LOCATION_CODE,
       L.ROWID ROW_ID,
       L.LOCATION_ID,
       TL.LOCATION_CODE,
       L.BILL_TO_SITE_FLAG,
       L.COUNTRY,
       TL.DESCRIPTION,
       L.DESIGNATED_RECEIVER_ID,
       L.IN_ORGANIZATION_FLAG,
       L.INACTIVE_DATE,
       L.INVENTORY_ORGANIZATION_ID,
       L.OFFICE_SITE_FLAG,
       L.RECEIVING_SITE_FLAG,
       L.SHIP_TO_LOCATION_ID,
       L.SHIP_TO_SITE_FLAG,
       L.TAX_NAME,
       L.STYLE,
       HR1.MEANING SHIP_TO_SITE,
       HR2.MEANING BILL_TO_SITE,
       HR3.MEANING OFFICE_SITE,
       HR4.MEANING RECEIVING_SITE,
       HR5.MEANING INTERNAL_SITE,
       L2TL.LOCATION_CODE SHIP_TO_LOCATION,
       FND.DESCRIPTIVE_FLEX_CONTEXT_NAME,
       L.ENTERED_BY,
       L.ADDRESS_LINE_1,
       L.ADDRESS_LINE_2,
       L.ADDRESS_LINE_3,
       L.POSTAL_CODE,
       L.REGION_1,
       L.REGION_2,
       L.REGION_3,
       L.TELEPHONE_NUMBER_1,
       L.TELEPHONE_NUMBER_2,
       L.TELEPHONE_NUMBER_3,
       L.TOWN_OR_CITY,
       L.ATTRIBUTE_CATEGORY,
       L.ATTRIBUTE1,
       L.ATTRIBUTE2,
       L.ATTRIBUTE3,
       L.ATTRIBUTE4,
       L.ATTRIBUTE5,
       L.ATTRIBUTE6,
       L.ATTRIBUTE7,
       L.ATTRIBUTE8,
       L.ATTRIBUTE9,
       L.ATTRIBUTE10,
       L.ATTRIBUTE11,
       L.ATTRIBUTE12,
       L.ATTRIBUTE13,
       L.ATTRIBUTE14,
       L.ATTRIBUTE15,
       L.ATTRIBUTE16,
       L.ATTRIBUTE17,
       L.ATTRIBUTE18,
       L.ATTRIBUTE19,
       L.ATTRIBUTE20,
       L.GLOBAL_ATTRIBUTE_CATEGORY,
       L.GLOBAL_ATTRIBUTE1,
       L.GLOBAL_ATTRIBUTE2,
       L.GLOBAL_ATTRIBUTE3,
       L.GLOBAL_ATTRIBUTE4,
       L.GLOBAL_ATTRIBUTE5,
       L.GLOBAL_ATTRIBUTE6,
       L.GLOBAL_ATTRIBUTE7,
       L.GLOBAL_ATTRIBUTE8,
       L.GLOBAL_ATTRIBUTE9,
       L.GLOBAL_ATTRIBUTE10,
       L.GLOBAL_ATTRIBUTE11,
       L.GLOBAL_ATTRIBUTE12,
       L.GLOBAL_ATTRIBUTE13,
       L.GLOBAL_ATTRIBUTE14,
       L.GLOBAL_ATTRIBUTE15,
       L.GLOBAL_ATTRIBUTE16,
       L.GLOBAL_ATTRIBUTE17,
       L.GLOBAL_ATTRIBUTE18,
       L.GLOBAL_ATTRIBUTE19,
       L.GLOBAL_ATTRIBUTE20,
       L.LAST_UPDATE_DATE,
       L.LAST_UPDATED_BY,
       L.LAST_UPDATE_LOGIN,
       L.CREATED_BY,
       L.CREATION_DATE,
       L.LOC_INFORMATION13,
       L.LOC_INFORMATION14,
       L.LOC_INFORMATION15,
       L.LOC_INFORMATION16,
       L.LOC_INFORMATION17,
       L.LOC_INFORMATION18,
       L.LOC_INFORMATION19,
       L.LOC_INFORMATION20,
       L.OBJECT_VERSION_NUMBER,
       L.BUSINESS_GROUP_ID + 0,
       L.LEGAL_ADDRESS_FLAG,
       L.TIMEZONE_CODE,
       DECODE(L.TIMEZONE_CODE,
              NULL,
              NULL,
              '(GMT ' || TO_CHAR(TRUNC(TZVL.GMT_OFFSET), 'S09') || ':' ||
              TO_CHAR(ABS(TZVL.GMT_OFFSET - TRUNC(TZVL.GMT_OFFSET)) * 60,
                      'FM900') || ') ' || TZVL.NAME)
  FROM HR_LOCATIONS_ALL           L,
       HR_LOCATIONS_ALL_TL        TL,
       HR_LOOKUPS                 HR1,
       HR_LOOKUPS                 HR2,
       HR_LOOKUPS                 HR3,
       HR_LOOKUPS                 HR4,
       HR_LOOKUPS                 HR5,
       HR_LOCATIONS_ALL_TL        L2TL,
       FND_DESCR_FLEX_CONTEXTS_TL FND,
       FND_TIMEZONES_VL           TZVL
 WHERE HR1.LOOKUP_TYPE(+) = 'YES_NO'
   AND HR1.LOOKUP_CODE(+) = L.SHIP_TO_SITE_FLAG
   AND HR2.LOOKUP_TYPE(+) = 'YES_NO'
   AND HR2.LOOKUP_CODE(+) = L.BILL_TO_SITE_FLAG
   AND HR3.LOOKUP_TYPE(+) = 'YES_NO'
   AND HR3.LOOKUP_CODE(+) = L.OFFICE_SITE_FLAG
   AND HR4.LOOKUP_TYPE(+) = 'YES_NO'
   AND HR4.LOOKUP_CODE(+) = L.RECEIVING_SITE_FLAG
   AND HR5.LOOKUP_TYPE(+) = 'YES_NO'
   AND HR5.LOOKUP_CODE(+) = L.IN_ORGANIZATION_FLAG
   AND L2TL.LOCATION_ID(+) = L.SHIP_TO_LOCATION_ID
   AND L.STYLE = FND.DESCRIPTIVE_FLEX_CONTEXT_CODE(+)
   AND TZVL.TIMEZONE_CODE(+) = L.TIMEZONE_CODE
   AND TZVL.ENABLED_FLAG(+) = 'Y'
   AND FND.APPLICATION_ID(+) = 800
   AND FND.DESCRIPTIVE_FLEXFIELD_NAME(+) = 'Address Location'
   AND FND.LANGUAGE(+) = userenv('LANG')
   AND L.LOCATION_ID = TL.LOCATION_ID
   AND TL.LANGUAGE = USERENV('LANG')
   AND /* 
       COMENTADO PORQUE O USUARIO NAO TEM ACESSO A PACKAGE DO APPS
       NVL(L.BUSINESS_GROUP_ID, NVL(HR_GENERAL.GET_BUSINESS_GROUP_ID, -99)) =
       NVL(HR_GENERAL.GET_BUSINESS_GROUP_ID, NVL(L.BUSINESS_GROUP_ID, -99))
       
   AND */ DECODE(L2TL.location_id, null, '1', l2tl.language) =
       DECODE(L2tl.location_id, null, '1', userenv('LANG'));


create or replace view mdb_wsh_container_items_v as
select "MASTER_LOCATION_ID","MASTER_ORGANIZATION_ID","CONTAINER_ITEM_ID","LOAD_ITEM_ID","MAX_LOAD_QUANTITY","ATTRIBUTE_CATEGORY","ATTRIBUTE1","ATTRIBUTE2","ATTRIBUTE3","ATTRIBUTE4","ATTRIBUTE5","ATTRIBUTE6","ATTRIBUTE7","ATTRIBUTE8","ATTRIBUTE9","ATTRIBUTE10","ATTRIBUTE11","ATTRIBUTE12","ATTRIBUTE13","ATTRIBUTE14","ATTRIBUTE15","CREATION_DATE","CREATED_BY","LAST_UPDATE_DATE","LAST_UPDATED_BY","LAST_UPDATE_LOGIN","PROGRAM_APPLICATION_ID","PROGRAM_ID","PROGRAM_UPDATE_DATE","REQUEST_ID","PREFERRED_FLAG"
               from WSH_CONTAINER_ITEMS a
              where a.preferred_flag='Y';  
              
CREATE OR REPLACE VIEW MTL_CATEGORIES_VL AS
SELECT B.ROWID ROW_ID , B.CATEGORY_ID , B.STRUCTURE_ID , B.DISABLE_DATE , B.WEB_STATUS , B.SUPPLIER_ENABLED_FLAG , B.SEGMENT1 , B.SEGMENT2 , B.SEGMENT3 , B.SEGMENT4 , B.SEGMENT5 , B.SEGMENT6 , B.SEGMENT7 , B.SEGMENT8 , B.SEGMENT9 , B.SEGMENT10 , B.SEGMENT11 , B.SEGMENT12 , B.SEGMENT13 , B.SEGMENT14 , B.SEGMENT15 , B.SEGMENT16 , B.SEGMENT17 , B.SEGMENT18 , B.SEGMENT19 , B.SEGMENT20 , B.SUMMARY_FLAG , B.ENABLED_FLAG , B.START_DATE_ACTIVE , B.END_DATE_ACTIVE , B.ATTRIBUTE_CATEGORY , B.ATTRIBUTE1 , B.ATTRIBUTE2 , B.ATTRIBUTE3 , B.ATTRIBUTE4 , B.ATTRIBUTE5 , B.ATTRIBUTE6 , B.ATTRIBUTE7 , B.ATTRIBUTE8 , B.ATTRIBUTE9 , B.ATTRIBUTE10 , B.ATTRIBUTE11 , B.ATTRIBUTE12 , B.ATTRIBUTE13 , B.ATTRIBUTE14 , B.ATTRIBUTE15 , B.LAST_UPDATE_DATE , B.LAST_UPDATED_BY , B.CREATION_DATE , B.CREATED_BY , B.LAST_UPDATE_LOGIN , B.REQUEST_ID , B.PROGRAM_APPLICATION_ID , B.PROGRAM_ID , B.PROGRAM_UPDATE_DATE , T.DESCRIPTION FROM MTL_CATEGORIES_TL T , MTL_CATEGORIES_B B WHERE B.CATEGORY_ID = T.CATEGORY_ID AND T.LANGUAGE = userenv('LANG');			  


CREATE OR REPLACE VIEW MTL_CATEGORY_SETS_VL AS
SELECT B.ROWID ROW_ID , B.CATEGORY_SET_ID , B.STRUCTURE_ID , B.VALIDATE_FLAG , B.CONTROL_LEVEL , B.DEFAULT_CATEGORY_ID , B.LAST_UPDATE_DATE , B.LAST_UPDATED_BY , B.CREATION_DATE , B.CREATED_BY , B.LAST_UPDATE_LOGIN , B.REQUEST_ID , B.PROGRAM_APPLICATION_ID , B.PROGRAM_ID , B.PROGRAM_UPDATE_DATE , T.CATEGORY_SET_NAME , T.DESCRIPTION , B.MULT_ITEM_CAT_ASSIGN_FLAG , B.CONTROL_LEVEL_UPDATEABLE_FLAG , B.MULT_ITEM_CAT_UPDATEABLE_FLAG , B.VALIDATE_FLAG_UPDATEABLE_FLAG , B.HIERARCHY_ENABLED FROM MTL_CATEGORY_SETS_TL T , MTL_CATEGORY_SETS_B B WHERE B.CATEGORY_SET_ID = T.CATEGORY_SET_ID AND T.LANGUAGE = userenv('LANG');


CREATE SYNONYM MTL_CATEGORY_SETS for MTL_CATEGORY_SETS_VL;

CREATE OR REPLACE VIEW MTL_CATEGORIES_VL AS
SELECT B.ROWID ROW_ID,
       B.CATEGORY_ID,
       B.STRUCTURE_ID,
       B.DISABLE_DATE,
       B.WEB_STATUS,
       B.SUPPLIER_ENABLED_FLAG,
       B.SEGMENT1,
       B.SEGMENT2,
       B.SEGMENT3,
       B.SEGMENT4,
       B.SEGMENT5,
       B.SEGMENT6,
       B.SEGMENT7,
       B.SEGMENT8,
       B.SEGMENT9,
       B.SEGMENT10,
       B.SEGMENT11,
       B.SEGMENT12,
       B.SEGMENT13,
       B.SEGMENT14,
       B.SEGMENT15,
       B.SEGMENT16,
       B.SEGMENT17,
       B.SEGMENT18,
       B.SEGMENT19,
       B.SEGMENT20,
       B.SUMMARY_FLAG,
       B.ENABLED_FLAG,
       B.START_DATE_ACTIVE,
       B.END_DATE_ACTIVE,
       B.ATTRIBUTE_CATEGORY,
       B.ATTRIBUTE1,
       B.ATTRIBUTE2,
       B.ATTRIBUTE3,
       B.ATTRIBUTE4,
       B.ATTRIBUTE5,
       B.ATTRIBUTE6,
       B.ATTRIBUTE7,
       B.ATTRIBUTE8,
       B.ATTRIBUTE9,
       B.ATTRIBUTE10,
       B.ATTRIBUTE11,
       B.ATTRIBUTE12,
       B.ATTRIBUTE13,
       B.ATTRIBUTE14,
       B.ATTRIBUTE15,
       B.LAST_UPDATE_DATE,
       B.LAST_UPDATED_BY,
       B.CREATION_DATE,
       B.CREATED_BY,
       B.LAST_UPDATE_LOGIN,
       B.REQUEST_ID,
       B.PROGRAM_APPLICATION_ID,
       B.PROGRAM_ID,
       B.PROGRAM_UPDATE_DATE,
       T.DESCRIPTION
  FROM MTL_CATEGORIES_TL T, MTL_CATEGORIES_B B
 WHERE B.CATEGORY_ID = T.CATEGORY_ID
   AND T.LANGUAGE = userenv('LANG');
   
CREATE SYNONYM MTL_CATEGORIES FOR MTL_CATEGORIES_VL;

/**/
CREATE OR REPLACE VIEW HR_LOCATIONS_ALL_V
(location_id, location_code, location_use, business_group_id, description, ship_to_location_id, ship_to_site_flag, receiving_site_flag, bill_to_site_flag, in_organization_flag, office_site_flag, designated_receiver_id, inventory_organization_id, tax_name, inactive_date, style, address_line_1, address_line_2, address_line_3, town_or_city, country, postal_code, region_1, region_2, region_3, telephone_number_1, telephone_number_2, telephone_number_3, loc_information13, loc_information14, loc_information15, loc_information16, loc_information17, loc_information18, loc_information19, loc_information20, attribute_category, attribute1, attribute2, attribute3, attribute4, attribute5, attribute6, attribute7, attribute8, attribute9, attribute10, attribute11, attribute12, attribute13, attribute14, attribute15, attribute16, attribute17, attribute18, attribute19, attribute20, global_attribute_category, global_attribute1, global_attribute2, global_attribute3, global_attribute4, global_attribute5, global_attribute6, global_attribute7, global_attribute8, global_attribute9, global_attribute10, global_attribute11, global_attribute12, global_attribute13, global_attribute14, global_attribute15, global_attribute16, global_attribute17, global_attribute18, global_attribute19, global_attribute20, last_update_date, last_updated_by, last_update_login, created_by, creation_date, entered_by, tp_header_id, ece_tp_location_code, object_version_number, legal_address_flag, timezone_code)
AS
SELECT loc.location_id,
       lot.location_code,
       'HR',
       loc.business_group_id + 0 business_group_id,
       lot.description,
       loc.ship_to_location_id,
       loc.ship_to_site_flag,
       loc.receiving_site_flag,
       loc.bill_to_site_flag,
       loc.in_organization_flag,
       loc.office_site_flag,
       loc.designated_receiver_id,
       loc.inventory_organization_id,
       loc.tax_name,
       loc.inactive_date,
       loc.style,
       loc.address_line_1,
       loc.address_line_2,
       loc.address_line_3,
       loc.town_or_city,
       loc.country,
       loc.postal_code,
       loc.region_1,
       loc.region_2,
       loc.region_3,
       loc.telephone_number_1,
       loc.telephone_number_2,
       loc.telephone_number_3,
       loc.loc_information13,
       loc.loc_information14,
       loc.loc_information15,
       loc.loc_information16,
       loc.loc_information17,
       loc.loc_information18,
       loc.loc_information19,
       loc.loc_information20,
       loc.attribute_category,
       loc.attribute1,
       loc.attribute2,
       loc.attribute3,
       loc.attribute4,
       loc.attribute5,
       loc.attribute6,
       loc.attribute7,
       loc.attribute8,
       loc.attribute9,
       loc.attribute10,
       loc.attribute11,
       loc.attribute12,
       loc.attribute13,
       loc.attribute14,
       loc.attribute15,
       loc.attribute16,
       loc.attribute17,
       loc.attribute18,
       loc.attribute19,
       loc.attribute20,
       loc.global_attribute_category,
       loc.global_attribute1,
       loc.global_attribute2,
       loc.global_attribute3,
       loc.global_attribute4,
       loc.global_attribute5,
       loc.global_attribute6,
       loc.global_attribute7,
       loc.global_attribute8,
       loc.global_attribute9,
       loc.global_attribute10,
       loc.global_attribute11,
       loc.global_attribute12,
       loc.global_attribute13,
       loc.global_attribute14,
       loc.global_attribute15,
       loc.global_attribute16,
       loc.global_attribute17,
       loc.global_attribute18,
       loc.global_attribute19,
       loc.global_attribute20,
       loc.last_update_date,
       loc.last_updated_by,
       loc.last_update_login,
       loc.created_by,
       loc.creation_date,
       loc.entered_by,
       loc.tp_header_id,
       loc.ece_tp_location_code,
       loc.object_version_number,
       loc.legal_address_flag,
       loc.timezone_code
  from hr_locations_all loc, hr_locations_all_tl lot
 WHERE 
 	/* COMENTADO POR QUESTÃO DE ACESSO DO USUÁRIO MDB_IMDB NO SCHEMA DA PACKAGE
 		nvl(loc.business_group_id,
           nvl(hr_general.get_business_group_id, -99)) =
       nvl(hr_general.get_business_group_id, -99)
   and */
   loc.location_id = lot.location_id
   and lot.language = userenv('LANG');
   
CREATE OR REPLACE VIEW  AR_LOCATION_ACCOUNTS AS
SELECT LOCATION_VALUE_ACCOUNT_ID,
       LOCATION_SEGMENT_ID,
       TAX_ACCOUNT_CCID,
       INTERIM_TAX_CCID,
       ADJ_CCID,
       EDISC_CCID,
       UNEDISC_CCID,
       FINCHRG_CCID,
       ADJ_NON_REC_TAX_CCID,
       EDISC_NON_REC_TAX_CCID,
       UNEDISC_NON_REC_TAX_CCID,
       FINCHRG_NON_REC_TAX_CCID,
       CREATED_BY,
       CREATION_DATE,
       LAST_UPDATED_BY,
       LAST_UPDATE_DATE,
       LAST_UPDATE_LOGIN,
       REQUEST_ID,
       PROGRAM_APPLICATION_ID,
       PROGRAM_ID,
       PROGRAM_UPDATE_DATE,
       ATTRIBUTE_CATEGORY,
       ATTRIBUTE1,
       ATTRIBUTE2,
       ATTRIBUTE3,
       ATTRIBUTE4,
       ATTRIBUTE5,
       ATTRIBUTE6,
       ATTRIBUTE7,
       ATTRIBUTE8,
       ATTRIBUTE9,
       ATTRIBUTE10,
       ATTRIBUTE11,
       ATTRIBUTE12,
       ATTRIBUTE13,
       ATTRIBUTE14,
       ATTRIBUTE15,
       ORG_ID
  from AR_LOCATION_ACCOUNTS_ALL
 WHERE NVL(ORG_ID,
           NVL(TO_NUMBER(DECODE(SUBSTRB(USERENV('CLIENT_INFO'), 1, 1),
                                ' ',
                                NULL,
                                SUBSTRB(USERENV('CLIENT_INFO'), 1, 10))),
               -99)) =
       NVL(TO_NUMBER(DECODE(SUBSTRB(USERENV('CLIENT_INFO'), 1, 1),
                            ' ',
                            NULL,
                            SUBSTRB(USERENV('CLIENT_INFO'), 1, 10))),
           -99);


CREATE OR REPLACE VIEW  AR_LOCATION_ACCOUNTS AS
SELECT LOCATION_VALUE_ACCOUNT_ID,
       LOCATION_SEGMENT_ID,
       TAX_ACCOUNT_CCID,
       INTERIM_TAX_CCID,
       ADJ_CCID,
       EDISC_CCID,
       UNEDISC_CCID,
       FINCHRG_CCID,
       ADJ_NON_REC_TAX_CCID,
       EDISC_NON_REC_TAX_CCID,
       UNEDISC_NON_REC_TAX_CCID,
       FINCHRG_NON_REC_TAX_CCID,
       CREATED_BY,
       CREATION_DATE,
       LAST_UPDATED_BY,
       LAST_UPDATE_DATE,
       LAST_UPDATE_LOGIN,
       REQUEST_ID,
       PROGRAM_APPLICATION_ID,
       PROGRAM_ID,
       PROGRAM_UPDATE_DATE,
       ATTRIBUTE_CATEGORY,
       ATTRIBUTE1,
       ATTRIBUTE2,
       ATTRIBUTE3,
       ATTRIBUTE4,
       ATTRIBUTE5,
       ATTRIBUTE6,
       ATTRIBUTE7,
       ATTRIBUTE8,
       ATTRIBUTE9,
       ATTRIBUTE10,
       ATTRIBUTE11,
       ATTRIBUTE12,
       ATTRIBUTE13,
       ATTRIBUTE14,
       ATTRIBUTE15,
       ORG_ID
  from AR_LOCATION_ACCOUNTS_ALL
 WHERE NVL(ORG_ID,
           NVL(TO_NUMBER(DECODE(SUBSTRB(USERENV('CLIENT_INFO'), 1, 1),
                                ' ',
                                NULL,
                                SUBSTRB(USERENV('CLIENT_INFO'), 1, 10))),
               -99)) =
       NVL(TO_NUMBER(DECODE(SUBSTRB(USERENV('CLIENT_INFO'), 1, 1),
                            ' ',
                            NULL,
                            SUBSTRB(USERENV('CLIENT_INFO'), 1, 10))),
           -99);

CREATE OR REPLACE VIEW  AR_LOCATION_VALUES_V AS
SELECT ARLV.ROWID                        ROW_ID,
       ARLV.LOCATION_SEGMENT_ID          LOCATION_SEGMENT_ID,
       ARLV.LOCATION_SEGMENT_USER_VALUE  LOCATION_SEGMENT_USER_VALUE,
       ARLV.LOCATION_STRUCTURE_ID        LOCATION_STRUCTURE_ID,
       ARLV.LOCATION_SEGMENT_QUALIFIER   LOCATION_SEGMENT_QUALIFIER,
       ARLV.LOCATION_SEGMENT_VALUE       LOCATION_SEGMENT_VALUE,
       ARLV.LOCATION_SEGMENT_DESCRIPTION LOCATION_SEGMENT_DESCRIPTION,
       ARLV.PARENT_SEGMENT_ID            PARENT_SEGMENT_ID,
       ARLVA.LOCATION_VALUE_ACCOUNT_ID   LOCATION_VALUE_ACCOUNT_ID,
       ARLVA.TAX_ACCOUNT_CCID            TAX_ACCOUNT_CCID,
       ARLVA.INTERIM_TAX_CCID            INTERIM_TAX_CCID,
       ARLVA.ADJ_CCID                    ADJ_CCID,
       ARLVA.EDISC_CCID                  EDISC_CCID,
       ARLVA.UNEDISC_CCID                UNEDISC_CCID,
       ARLVA.FINCHRG_CCID                FINCHRG_CCID,
       ARLVA.ADJ_NON_REC_TAX_CCID        ADJ_NON_REC_TAX_CCID,
       ARLVA.EDISC_NON_REC_TAX_CCID      EDISC_NON_REC_TAX_CCID,
       ARLVA.UNEDISC_NON_REC_TAX_CCID    UNEDISC_NON_REC_TAX_CCID,
       ARLVA.FINCHRG_NON_REC_TAX_CCID    FINCHRG_NON_REC_TAX_CCID,
       ARLV.ATTRIBUTE_CATEGORY           ATTRIBUTE_CATEGORY,
       ARLV.ATTRIBUTE1                   ATTRIBUTE1,
       ARLV.ATTRIBUTE2                   ATTRIBUTE2,
       ARLV.ATTRIBUTE3                   ATTRIBUTE3,
       ARLV.ATTRIBUTE4                   ATTRIBUTE4,
       ARLV.ATTRIBUTE5                   ATTRIBUTE5,
       ARLV.ATTRIBUTE6                   ATTRIBUTE6,
       ARLV.ATTRIBUTE7                   ATTRIBUTE7,
       ARLV.ATTRIBUTE8                   ATTRIBUTE8,
       ARLV.ATTRIBUTE9                   ATTRIBUTE9,
       ARLV.ATTRIBUTE10                  ATTRIBUTE10,
       ARLV.ATTRIBUTE11                  ATTRIBUTE11,
       ARLV.ATTRIBUTE12                  ATTRIBUTE12,
       ARLV.ATTRIBUTE13                  ATTRIBUTE13,
       ARLV.ATTRIBUTE14                  ATTRIBUTE14,
       ARLV.ATTRIBUTE15                  ATTRIBUTE15,
       ARLVA.CREATED_BY                  CREATED_BY,
       ARLVA.CREATION_DATE               CREATION_DATE,
       ARLVA.LAST_UPDATED_BY             LAST_UPDATED_BY,
       ARLVA.LAST_UPDATE_DATE            LAST_UPDATE_DATE,
       ARLVA.LAST_UPDATE_LOGIN           LAST_UPDATE_LOGIN,
       ARLVA.REQUEST_ID                  REQUEST_ID,
       ARLVA.PROGRAM_APPLICATION_ID      PROGRAM_APPLICATION_ID,
       ARLVA.PROGRAM_ID                  PROGRAM_ID,
       ARLVA.PROGRAM_UPDATE_DATE         PROGRAM_UPDATE_DATE,
       ARLV.GLOBAL_ATTRIBUTE_CATEGORY    GLOBAL_ATTRIBUTE_CATEGORY,
       ARLV.GLOBAL_ATTRIBUTE1            GLOBAL_ATTRIBUTE1,
       ARLV.GLOBAL_ATTRIBUTE2            GLOBAL_ATTRIBUTE2,
       ARLV.GLOBAL_ATTRIBUTE3            GLOBAL_ATTRIBUTE3,
       ARLV.GLOBAL_ATTRIBUTE4            GLOBAL_ATTRIBUTE4,
       ARLV.GLOBAL_ATTRIBUTE5            GLOBAL_ATTRIBUTE5,
       ARLV.GLOBAL_ATTRIBUTE6            GLOBAL_ATTRIBUTE6,
       ARLV.GLOBAL_ATTRIBUTE7            GLOBAL_ATTRIBUTE7,
       ARLV.GLOBAL_ATTRIBUTE8            GLOBAL_ATTRIBUTE8,
       ARLV.GLOBAL_ATTRIBUTE9            GLOBAL_ATTRIBUTE9,
       ARLV.GLOBAL_ATTRIBUTE10           GLOBAL_ATTRIBUTE10,
       ARLV.GLOBAL_ATTRIBUTE11           GLOBAL_ATTRIBUTE11,
       ARLV.GLOBAL_ATTRIBUTE12           GLOBAL_ATTRIBUTE12,
       ARLV.GLOBAL_ATTRIBUTE13           GLOBAL_ATTRIBUTE13,
       ARLV.GLOBAL_ATTRIBUTE14           GLOBAL_ATTRIBUTE14,
       ARLV.GLOBAL_ATTRIBUTE15           GLOBAL_ATTRIBUTE15,
       ARLV.GLOBAL_ATTRIBUTE16           GLOBAL_ATTRIBUTE16,
       ARLV.GLOBAL_ATTRIBUTE17           GLOBAL_ATTRIBUTE17,
       ARLV.GLOBAL_ATTRIBUTE18           GLOBAL_ATTRIBUTE18,
       ARLV.GLOBAL_ATTRIBUTE19           GLOBAL_ATTRIBUTE19,
       ARLV.GLOBAL_ATTRIBUTE20           GLOBAL_ATTRIBUTE20
  FROM AR_LOCATION_VALUES ARLV, AR_LOCATION_ACCOUNTS ARLVA
 WHERE ARLV.LOCATION_SEGMENT_ID = ARLVA.LOCATION_SEGMENT_ID(+);

           